# Generated by Django 4.2.6 on 2024-08-27 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_product_trader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='trader',
            new_name='trader_name',
        ),
    ]
